# Generated by Django 6.0.2 on 2026-02-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Ключ активации')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента (для себя)')),
                ('expiration_date', models.DateTimeField(verbose_name='Действует до')),
                ('activation_limit', models.PositiveIntegerField(default=1, verbose_name='Лимит активаций (шт)')),
                ('current_activations', models.PositiveIntegerField(default=0, editable=False, verbose_name='Текущее кол-во активаций')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ключ активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwid', models.CharField(max_length=255, verbose_name='HWID компьютера')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='license_module.license')),
            ],
            options={
                'verbose_name': 'Активация (HWID)',
                'verbose_name_plural': 'Активации',
                'unique_together': {('license', 'hwid')},
            },
        ),
    ]
